"""Documentos sueltos por instalacion y visibilidad interna/publica en observaciones

Revision ID: 5662cfc2a91f
Revises: 9d494009dc74
Create Date: 2026-08-13 21:34:51.790130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5662cfc2a91f'
down_revision = '9d494009dc74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instalacion_id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_documento', sa.Date(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=300), nullable=False),
    sa.Column('subido_por_id', sa.Integer(), nullable=True),
    sa.Column('fecha_carga', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['instalacion_id'], ['instalaciones.id'], ),
    sa.ForeignKeyConstraint(['subido_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documentos_equipo_id'), ['equipo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_instalacion_id'), ['instalacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_subido_por_id'), ['subido_por_id'], unique=False)

    with op.batch_alter_table('observaciones', schema=None) as batch_op:
        # server_default para que las filas existentes queden en 'Cliente'
        # (comportamiento de siempre) en vez de romper el NOT NULL; se cae
        # después porque el default real lo maneja el modelo (Python-side).
        batch_op.add_column(sa.Column('visibilidad', sa.String(length=20), nullable=False, server_default='Cliente'))

    with op.batch_alter_table('observaciones', schema=None) as batch_op:
        batch_op.alter_column('visibilidad', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observaciones', schema=None) as batch_op:
        batch_op.drop_column('visibilidad')

    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documentos_subido_por_id'))
        batch_op.drop_index(batch_op.f('ix_documentos_instalacion_id'))
        batch_op.drop_index(batch_op.f('ix_documentos_equipo_id'))

    op.drop_table('documentos')
    # ### end Alembic commands ###
