"""modulo bie: ficha de inspeccion y mangueras

Revision ID: 6edccfafefa3
Revises: 151e1d0779df
Create Date: 2026-08-28 18:51:46.414579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6edccfafefa3'
down_revision = '151e1d0779df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mangueras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instalacion_id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=True),
    sa.Column('ubicacion_libre', sa.String(length=100), nullable=True),
    sa.Column('numero_serie', sa.String(length=50), nullable=False),
    sa.Column('diametro', sa.String(length=10), nullable=False),
    sa.Column('longitud_metros', sa.Float(), nullable=True),
    sa.Column('material', sa.String(length=30), nullable=True),
    sa.Column('lugar_origen', sa.String(length=150), nullable=False),
    sa.Column('fecha_ultima_ph', sa.Date(), nullable=True),
    sa.Column('fecha_vencimiento_ph', sa.Date(), nullable=True),
    sa.Column('resultado_ultima_ph', sa.String(length=20), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['instalacion_id'], ['instalaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mangueras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mangueras_equipo_id'), ['equipo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mangueras_instalacion_id'), ['instalacion_id'], unique=False)

    op.create_table('notas_mantenimiento_manguera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manguera_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('realizado_por_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manguera_id'], ['mangueras.id'], ),
    sa.ForeignKeyConstraint(['realizado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notas_mantenimiento_manguera', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notas_mantenimiento_manguera_manguera_id'), ['manguera_id'], unique=False)

    op.create_table('reubicaciones_manguera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manguera_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('origen', sa.String(length=150), nullable=False),
    sa.Column('destino', sa.String(length=150), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('realizado_por_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manguera_id'], ['mangueras.id'], ),
    sa.ForeignKeyConstraint(['realizado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reubicaciones_manguera', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reubicaciones_manguera_manguera_id'), ['manguera_id'], unique=False)

    op.create_table('inspecciones_bie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('item_visita_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('fecha_prueba_boca', sa.Date(), nullable=True),
    sa.Column('resultado_prueba_boca', sa.String(length=20), nullable=True),
    sa.Column('veredicto', sa.String(length=30), nullable=False),
    sa.Column('dictamen', sa.Text(), nullable=True),
    sa.Column('observacion_id', sa.Integer(), nullable=True),
    sa.Column('realizado_por_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['item_visita_id'], ['items_visita.id'], ),
    sa.ForeignKeyConstraint(['observacion_id'], ['observaciones.id'], ),
    sa.ForeignKeyConstraint(['realizado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspecciones_bie', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspecciones_bie_equipo_id'), ['equipo_id'], unique=False)

    op.create_table('pruebas_hidrostaticas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manguera_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('presion_aplicada', sa.Float(), nullable=True),
    sa.Column('tiempo_minutos', sa.Float(), nullable=True),
    sa.Column('resultado', sa.String(length=20), nullable=False),
    sa.Column('certificado', sa.String(length=150), nullable=True),
    sa.Column('observacion_id', sa.Integer(), nullable=True),
    sa.Column('realizado_por_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manguera_id'], ['mangueras.id'], ),
    sa.ForeignKeyConstraint(['observacion_id'], ['observaciones.id'], ),
    sa.ForeignKeyConstraint(['realizado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pruebas_hidrostaticas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pruebas_hidrostaticas_manguera_id'), ['manguera_id'], unique=False)

    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_bie', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('diametro_nominal', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('tipo_puntero', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('tipo_racor', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('estado_racor', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('llave_spanner', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('valvula_operable', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('manometro_bar', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('estado_gabinete', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.drop_column('estado_gabinete')
        batch_op.drop_column('manometro_bar')
        batch_op.drop_column('valvula_operable')
        batch_op.drop_column('llave_spanner')
        batch_op.drop_column('estado_racor')
        batch_op.drop_column('tipo_racor')
        batch_op.drop_column('tipo_puntero')
        batch_op.drop_column('diametro_nominal')
        batch_op.drop_column('tipo_bie')

    with op.batch_alter_table('pruebas_hidrostaticas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pruebas_hidrostaticas_manguera_id'))

    op.drop_table('pruebas_hidrostaticas')
    with op.batch_alter_table('inspecciones_bie', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspecciones_bie_equipo_id'))

    op.drop_table('inspecciones_bie')
    with op.batch_alter_table('reubicaciones_manguera', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reubicaciones_manguera_manguera_id'))

    op.drop_table('reubicaciones_manguera')
    with op.batch_alter_table('notas_mantenimiento_manguera', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notas_mantenimiento_manguera_manguera_id'))

    op.drop_table('notas_mantenimiento_manguera')
    with op.batch_alter_table('mangueras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mangueras_instalacion_id'))
        batch_op.drop_index(batch_op.f('ix_mangueras_equipo_id'))

    op.drop_table('mangueras')
    # ### end Alembic commands ###
