"""incluir_en_carga_combinada en servicios_tipo y tipos_formulario

Revision ID: 962f0924f144
Revises: dc703fe2398f
Create Date: 2026-08-18 21:25:32.674176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '962f0924f144'
down_revision = 'dc703fe2398f'
branch_labels = None
depends_on = None


def upgrade():
    # server_default para que las filas existentes (servicios_tipo /
    # tipos_formulario ya cargados) queden en True al agregar la columna
    # NOT NULL -- se saca el default después para que quede a cargo del
    # modelo de ahí en más. SQLite es permisivo con "NOT NULL sin default"
    # sobre una tabla con filas, Postgres no -- mismo criterio que la
    # migración 5662cfc2a91f (columna "visibilidad").
    with op.batch_alter_table('servicios_tipo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('incluir_en_carga_combinada', sa.Boolean(), server_default=sa.true(), nullable=False))

    with op.batch_alter_table('tipos_formulario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('incluir_en_carga_combinada', sa.Boolean(), server_default=sa.true(), nullable=False))

    with op.batch_alter_table('servicios_tipo', schema=None) as batch_op:
        batch_op.alter_column('incluir_en_carga_combinada', server_default=None)

    with op.batch_alter_table('tipos_formulario', schema=None) as batch_op:
        batch_op.alter_column('incluir_en_carga_combinada', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipos_formulario', schema=None) as batch_op:
        batch_op.drop_column('incluir_en_carga_combinada')

    with op.batch_alter_table('servicios_tipo', schema=None) as batch_op:
        batch_op.drop_column('incluir_en_carga_combinada')

    # ### end Alembic commands ###
