"""Indices en columnas foreign key

Revision ID: dea312812c67
Revises: e6b4f82e9468
Create Date: 2026-08-12 15:37:55.875541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea312812c67'
down_revision = 'e6b4f82e9468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_empresa_id'), ['empresa_id'], unique=False)

    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contratos_instalacion_id'), ['instalacion_id'], unique=False)

    with op.batch_alter_table('coordinacion_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coordinacion_audit_solicitud_id'), ['solicitud_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coordinacion_audit_usuario_id'), ['usuario_id'], unique=False)

    with op.batch_alter_table('ensayos_caudal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ensayos_caudal_creado_por_id'), ['creado_por_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ensayos_caudal_equipo_id'), ['equipo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ensayos_caudal_item_visita_id'), ['item_visita_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ensayos_caudal_validado_por_id'), ['validado_por_id'], unique=False)

    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipos_instalacion_id'), ['instalacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipos_manifold_id'), ['manifold_id'], unique=False)

    with op.batch_alter_table('formularios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_formularios_equipo_id'), ['equipo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_formularios_item_visita_id'), ['item_visita_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_formularios_tipo_formulario_id'), ['tipo_formulario_id'], unique=False)

    with op.batch_alter_table('fotos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fotos_equipo_id'), ['equipo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fotos_instalacion_id'), ['instalacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fotos_item_visita_id'), ['item_visita_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fotos_observacion_id'), ['observacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fotos_subido_por_id'), ['subido_por_id'], unique=False)

    with op.batch_alter_table('instalaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instalaciones_cliente_id'), ['cliente_id'], unique=False)

    with op.batch_alter_table('items_visita', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_visita_equipo_id'), ['equipo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_visita_servicio_contrato_id'), ['servicio_contrato_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_visita_visita_id'), ['visita_id'], unique=False)

    with op.batch_alter_table('mensajes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mensajes_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mensajes_destinatario_id'), ['destinatario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mensajes_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mensajes_remitente_id'), ['remitente_id'], unique=False)

    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notificaciones_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificaciones_destinatario_id'), ['destinatario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificaciones_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificaciones_remitente_id'), ['remitente_id'], unique=False)

    with op.batch_alter_table('observaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observaciones_aprobado_por_id'), ['aprobado_por_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observaciones_confirmada_por_id'), ['confirmada_por_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observaciones_creado_por_id'), ['creado_por_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observaciones_equipo_id'), ['equipo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observaciones_instalacion_id'), ['instalacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observaciones_item_visita_id'), ['item_visita_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observaciones_reabierto_por_id'), ['reabierto_por_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observaciones_resuelto_por_id'), ['resuelto_por_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observaciones_ultima_visita_confirmada_id'), ['ultima_visita_confirmada_id'], unique=False)

    with op.batch_alter_table('ordenes_trabajo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ordenes_trabajo_instalacion_id'), ['instalacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordenes_trabajo_tecnico_id'), ['tecnico_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordenes_trabajo_visita_id'), ['visita_id'], unique=False)

    with op.batch_alter_table('presupuestos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_presupuestos_creado_por_id'), ['creado_por_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_presupuestos_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_presupuestos_observacion_id'), ['observacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_presupuestos_ot_correctiva_id'), ['ot_correctiva_id'], unique=False)

    with op.batch_alter_table('presupuestos_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_presupuestos_audit_presupuesto_id'), ['presupuesto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_presupuestos_audit_usuario_id'), ['usuario_id'], unique=False)

    with op.batch_alter_table('repuestos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repuestos_empresa_id'), ['empresa_id'], unique=False)

    with op.batch_alter_table('repuestos_usados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repuestos_usados_orden_trabajo_id'), ['orden_trabajo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repuestos_usados_repuesto_id'), ['repuesto_id'], unique=False)

    with op.batch_alter_table('servicios_contrato', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_servicios_contrato_contrato_id'), ['contrato_id'], unique=False)

    with op.batch_alter_table('servicios_tipo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_servicios_tipo_empresa_id'), ['empresa_id'], unique=False)

    with op.batch_alter_table('solicitudes_coordinacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitudes_coordinacion_contrato_id'), ['contrato_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitudes_coordinacion_coordinado_por_id'), ['coordinado_por_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitudes_coordinacion_visita_id'), ['visita_id'], unique=False)

    with op.batch_alter_table('tipos_formulario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tipos_formulario_cliente_id'), ['cliente_id'], unique=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_empresa_id'), ['empresa_id'], unique=False)

    with op.batch_alter_table('visitas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visitas_cerrada_por_id'), ['cerrada_por_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitas_contrato_id'), ['contrato_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitas_enviada_por_id'), ['enviada_por_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitas_instalacion_id'), ['instalacion_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitas_instalacion_id'))
        batch_op.drop_index(batch_op.f('ix_visitas_enviada_por_id'))
        batch_op.drop_index(batch_op.f('ix_visitas_contrato_id'))
        batch_op.drop_index(batch_op.f('ix_visitas_cerrada_por_id'))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_cliente_id'))

    with op.batch_alter_table('tipos_formulario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tipos_formulario_cliente_id'))

    with op.batch_alter_table('solicitudes_coordinacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitudes_coordinacion_visita_id'))
        batch_op.drop_index(batch_op.f('ix_solicitudes_coordinacion_coordinado_por_id'))
        batch_op.drop_index(batch_op.f('ix_solicitudes_coordinacion_contrato_id'))

    with op.batch_alter_table('servicios_tipo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servicios_tipo_empresa_id'))

    with op.batch_alter_table('servicios_contrato', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servicios_contrato_contrato_id'))

    with op.batch_alter_table('repuestos_usados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repuestos_usados_repuesto_id'))
        batch_op.drop_index(batch_op.f('ix_repuestos_usados_orden_trabajo_id'))

    with op.batch_alter_table('repuestos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repuestos_empresa_id'))

    with op.batch_alter_table('presupuestos_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presupuestos_audit_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_presupuestos_audit_presupuesto_id'))

    with op.batch_alter_table('presupuestos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presupuestos_ot_correctiva_id'))
        batch_op.drop_index(batch_op.f('ix_presupuestos_observacion_id'))
        batch_op.drop_index(batch_op.f('ix_presupuestos_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_presupuestos_creado_por_id'))

    with op.batch_alter_table('ordenes_trabajo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ordenes_trabajo_visita_id'))
        batch_op.drop_index(batch_op.f('ix_ordenes_trabajo_tecnico_id'))
        batch_op.drop_index(batch_op.f('ix_ordenes_trabajo_instalacion_id'))

    with op.batch_alter_table('observaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observaciones_ultima_visita_confirmada_id'))
        batch_op.drop_index(batch_op.f('ix_observaciones_resuelto_por_id'))
        batch_op.drop_index(batch_op.f('ix_observaciones_reabierto_por_id'))
        batch_op.drop_index(batch_op.f('ix_observaciones_item_visita_id'))
        batch_op.drop_index(batch_op.f('ix_observaciones_instalacion_id'))
        batch_op.drop_index(batch_op.f('ix_observaciones_equipo_id'))
        batch_op.drop_index(batch_op.f('ix_observaciones_creado_por_id'))
        batch_op.drop_index(batch_op.f('ix_observaciones_confirmada_por_id'))
        batch_op.drop_index(batch_op.f('ix_observaciones_aprobado_por_id'))

    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificaciones_remitente_id'))
        batch_op.drop_index(batch_op.f('ix_notificaciones_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_notificaciones_destinatario_id'))
        batch_op.drop_index(batch_op.f('ix_notificaciones_cliente_id'))

    with op.batch_alter_table('mensajes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mensajes_remitente_id'))
        batch_op.drop_index(batch_op.f('ix_mensajes_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_mensajes_destinatario_id'))
        batch_op.drop_index(batch_op.f('ix_mensajes_cliente_id'))

    with op.batch_alter_table('items_visita', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_visita_visita_id'))
        batch_op.drop_index(batch_op.f('ix_items_visita_servicio_contrato_id'))
        batch_op.drop_index(batch_op.f('ix_items_visita_equipo_id'))

    with op.batch_alter_table('instalaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instalaciones_cliente_id'))

    with op.batch_alter_table('fotos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fotos_subido_por_id'))
        batch_op.drop_index(batch_op.f('ix_fotos_observacion_id'))
        batch_op.drop_index(batch_op.f('ix_fotos_item_visita_id'))
        batch_op.drop_index(batch_op.f('ix_fotos_instalacion_id'))
        batch_op.drop_index(batch_op.f('ix_fotos_equipo_id'))

    with op.batch_alter_table('formularios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_formularios_tipo_formulario_id'))
        batch_op.drop_index(batch_op.f('ix_formularios_item_visita_id'))
        batch_op.drop_index(batch_op.f('ix_formularios_equipo_id'))

    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipos_manifold_id'))
        batch_op.drop_index(batch_op.f('ix_equipos_instalacion_id'))

    with op.batch_alter_table('ensayos_caudal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ensayos_caudal_validado_por_id'))
        batch_op.drop_index(batch_op.f('ix_ensayos_caudal_item_visita_id'))
        batch_op.drop_index(batch_op.f('ix_ensayos_caudal_equipo_id'))
        batch_op.drop_index(batch_op.f('ix_ensayos_caudal_creado_por_id'))

    with op.batch_alter_table('coordinacion_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coordinacion_audit_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_coordinacion_audit_solicitud_id'))

    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contratos_instalacion_id'))

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_empresa_id'))

    # ### end Alembic commands ###
