"""Esquema inicial

Revision ID: e6b4f82e9468
Revises: 
Create Date: 2026-08-12 15:35:48.759379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6b4f82e9468'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipos_equipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=40), nullable=False),
    sa.Column('categoria', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('direccion', sa.String(length=250), nullable=True),
    sa.Column('contacto', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repuestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('codigo', sa.String(length=60), nullable=True),
    sa.Column('unidad', sa.String(length=30), nullable=True),
    sa.Column('stock_actual', sa.Integer(), nullable=False),
    sa.Column('stock_minimo', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicios_tipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('schema_json', sa.Text(), nullable=False),
    sa.Column('por_equipo', sa.Boolean(), nullable=False),
    sa.Column('tipo_equipo_aplicable', sa.String(length=40), nullable=True),
    sa.Column('es_curva_caudal', sa.Boolean(), nullable=False),
    sa.Column('referencia_normativa', sa.String(length=200), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=60), nullable=True),
    sa.Column('oculto', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'nombre', name='uq_servicio_tipo_empresa_nombre')
    )
    op.create_table('instalaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('direccion', sa.String(length=250), nullable=True),
    sa.Column('fecha_alta', sa.Date(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipos_formulario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('schema_json', sa.Text(), nullable=False),
    sa.Column('por_equipo', sa.Boolean(), nullable=False),
    sa.Column('tipo_equipo_aplicable', sa.String(length=40), nullable=True),
    sa.Column('referencia_normativa', sa.String(length=200), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id', 'nombre', name='uq_tipo_formulario_cliente_nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=True),
    sa.Column('rol', sa.String(length=30), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('contratos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instalacion_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['instalacion_id'], ['instalaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instalacion_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('ubicacion', sa.String(length=250), nullable=True),
    sa.Column('manifold_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('modelo', sa.String(length=150), nullable=True),
    sa.Column('serie', sa.String(length=150), nullable=True),
    sa.Column('caudal_nominal', sa.Float(), nullable=True),
    sa.Column('presion_diseno', sa.Float(), nullable=True),
    sa.Column('presion_maxima', sa.Float(), nullable=True),
    sa.Column('presion_sobrecarga', sa.Float(), nullable=True),
    sa.Column('rpm_nominal', sa.Integer(), nullable=True),
    sa.Column('anio_fabricacion', sa.Integer(), nullable=True),
    sa.Column('otros_datos_placa', sa.Text(), nullable=True),
    sa.Column('tipo_motor', sa.String(length=20), nullable=True),
    sa.Column('motor_potencia_hp', sa.Float(), nullable=True),
    sa.Column('motor_voltaje', sa.Float(), nullable=True),
    sa.Column('motor_amperaje', sa.Float(), nullable=True),
    sa.Column('motor_fases', sa.Integer(), nullable=True),
    sa.Column('motor_marca_modelo', sa.String(length=150), nullable=True),
    sa.Column('motor_combustible_litros', sa.Float(), nullable=True),
    sa.Column('motor_horas_uso', sa.Float(), nullable=True),
    sa.Column('motor_estado_bateria', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['instalacion_id'], ['instalaciones.id'], ),
    sa.ForeignKeyConstraint(['manifold_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('remitente_id', sa.Integer(), nullable=False),
    sa.Column('destinatario_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('prioridad', sa.String(length=20), nullable=False),
    sa.Column('leido', sa.Boolean(), nullable=False),
    sa.Column('resuelto', sa.Boolean(), nullable=False),
    sa.Column('fecha_carga', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['destinatario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['remitente_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('destinatario_id', sa.Integer(), nullable=False),
    sa.Column('remitente_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('titulo', sa.String(length=250), nullable=False),
    sa.Column('enlace', sa.String(length=300), nullable=True),
    sa.Column('leido', sa.Boolean(), nullable=False),
    sa.Column('fecha_carga', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['destinatario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['remitente_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curvas_fabrica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('rpm_nominal', sa.Integer(), nullable=False),
    sa.Column('punto_0_presion', sa.Float(), nullable=False),
    sa.Column('punto_50_presion', sa.Float(), nullable=False),
    sa.Column('punto_100_presion', sa.Float(), nullable=False),
    sa.Column('punto_150_presion', sa.Float(), nullable=False),
    sa.Column('punto_0_potencia_kw', sa.Float(), nullable=True),
    sa.Column('punto_50_potencia_kw', sa.Float(), nullable=True),
    sa.Column('punto_100_potencia_kw', sa.Float(), nullable=True),
    sa.Column('punto_150_potencia_kw', sa.Float(), nullable=True),
    sa.Column('fecha_ingreso', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipo_id')
    )
    op.create_table('servicios_contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('frecuencia', sa.String(length=30), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('tipo_equipo_aplicable', sa.String(length=40), nullable=True),
    sa.Column('es_curva_caudal', sa.Boolean(), nullable=False),
    sa.Column('categoria', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instalacion_id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tecnico', sa.String(length=150), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('en_revision', sa.Boolean(), nullable=False),
    sa.Column('fecha_enviada_revision', sa.Date(), nullable=True),
    sa.Column('enviada_por_id', sa.Integer(), nullable=True),
    sa.Column('cerrada', sa.Boolean(), nullable=False),
    sa.Column('fecha_cierre', sa.Date(), nullable=True),
    sa.Column('notas_cierre', sa.Text(), nullable=True),
    sa.Column('cerrada_por_id', sa.Integer(), nullable=True),
    sa.Column('firma_cliente', sa.Text(), nullable=True),
    sa.Column('firma_tecnico', sa.Text(), nullable=True),
    sa.Column('nota_cliente', sa.Text(), nullable=True),
    sa.Column('nota_cliente_fecha', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['cerrada_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.ForeignKeyConstraint(['enviada_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['instalacion_id'], ['instalaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items_visita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visita_id', sa.Integer(), nullable=False),
    sa.Column('servicio_contrato_id', sa.Integer(), nullable=True),
    sa.Column('equipo_id', sa.Integer(), nullable=True),
    sa.Column('nombre_libre', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['servicio_contrato_id'], ['servicios_contrato.id'], ),
    sa.ForeignKeyConstraint(['visita_id'], ['visitas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordenes_trabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('instalacion_id', sa.Integer(), nullable=False),
    sa.Column('visita_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('prioridad', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('tecnico', sa.String(length=150), nullable=True),
    sa.Column('tecnico_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_apertura', sa.Date(), nullable=False),
    sa.Column('fecha_cierre', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['instalacion_id'], ['instalaciones.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['visita_id'], ['visitas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('solicitudes_coordinacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('coordinada', sa.Boolean(), nullable=False),
    sa.Column('fecha_coordinada', sa.Date(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('coordinado_por_id', sa.Integer(), nullable=True),
    sa.Column('fecha_coordinacion', sa.DateTime(), nullable=True),
    sa.Column('visita_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.ForeignKeyConstraint(['coordinado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['visita_id'], ['visitas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contrato_id', 'anio', 'mes', name='uq_solicitud_contrato_anio_mes')
    )
    op.create_table('coordinacion_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('fecha_anterior', sa.Date(), nullable=True),
    sa.Column('fecha_nueva', sa.Date(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('fecha_cambio', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes_coordinacion.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ensayos_caudal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('fecha_ensayo', sa.Date(), nullable=False),
    sa.Column('rpm_punto_0', sa.Integer(), nullable=False),
    sa.Column('presion_descarga_punto_0', sa.Float(), nullable=False),
    sa.Column('presion_succion_punto_0', sa.Float(), nullable=False),
    sa.Column('presion_neta_punto_0', sa.Float(), nullable=False),
    sa.Column('caudal_gpm_punto_0', sa.Float(), nullable=True),
    sa.Column('potencia_absorbida_punto_0', sa.Float(), nullable=True),
    sa.Column('rpm_punto_50', sa.Integer(), nullable=False),
    sa.Column('presion_descarga_punto_50', sa.Float(), nullable=False),
    sa.Column('presion_succion_punto_50', sa.Float(), nullable=False),
    sa.Column('presion_neta_punto_50', sa.Float(), nullable=False),
    sa.Column('caudal_gpm_punto_50', sa.Float(), nullable=True),
    sa.Column('potencia_absorbida_punto_50', sa.Float(), nullable=True),
    sa.Column('rpm_punto_100', sa.Integer(), nullable=False),
    sa.Column('presion_descarga_punto_100', sa.Float(), nullable=False),
    sa.Column('presion_succion_punto_100', sa.Float(), nullable=False),
    sa.Column('presion_neta_punto_100', sa.Float(), nullable=False),
    sa.Column('caudal_gpm_punto_100', sa.Float(), nullable=True),
    sa.Column('potencia_absorbida_punto_100', sa.Float(), nullable=True),
    sa.Column('rpm_punto_150', sa.Integer(), nullable=False),
    sa.Column('presion_descarga_punto_150', sa.Float(), nullable=False),
    sa.Column('presion_succion_punto_150', sa.Float(), nullable=False),
    sa.Column('presion_neta_punto_150', sa.Float(), nullable=False),
    sa.Column('caudal_gpm_punto_150', sa.Float(), nullable=True),
    sa.Column('potencia_absorbida_punto_150', sa.Float(), nullable=True),
    sa.Column('temperatura_ambiente', sa.Float(), nullable=True),
    sa.Column('presion_atmosferica_mbar', sa.Float(), nullable=True),
    sa.Column('presion_succion_estatica', sa.Float(), nullable=True),
    sa.Column('normativa_aplicable', sa.Text(), nullable=True),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('item_visita_id', sa.Integer(), nullable=True),
    sa.Column('estado_revision', sa.String(length=20), nullable=False),
    sa.Column('validado_por_id', sa.Integer(), nullable=True),
    sa.Column('fecha_validacion', sa.DateTime(), nullable=True),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('resultado_manual', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['item_visita_id'], ['items_visita.id'], ),
    sa.ForeignKeyConstraint(['validado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipo_id', 'fecha_ensayo', name='uq_ensayo_equipo_fecha')
    )
    op.create_table('formularios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_visita_id', sa.Integer(), nullable=False),
    sa.Column('tipo_formulario_id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=True),
    sa.Column('datos_json', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['item_visita_id'], ['items_visita.id'], ),
    sa.ForeignKeyConstraint(['tipo_formulario_id'], ['tipos_formulario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instalacion_id', sa.Integer(), nullable=False),
    sa.Column('item_visita_id', sa.Integer(), nullable=True),
    sa.Column('equipo_id', sa.Integer(), nullable=True),
    sa.Column('clasificacion', sa.String(length=40), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_carga', sa.Date(), nullable=False),
    sa.Column('resuelto', sa.Boolean(), nullable=False),
    sa.Column('fecha_resolucion', sa.Date(), nullable=True),
    sa.Column('estado_revision', sa.String(length=20), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('aprobado_por_id', sa.Integer(), nullable=True),
    sa.Column('fecha_aprobacion', sa.Date(), nullable=True),
    sa.Column('resuelto_por_id', sa.Integer(), nullable=True),
    sa.Column('reabierto_por_id', sa.Integer(), nullable=True),
    sa.Column('fecha_reapertura', sa.Date(), nullable=True),
    sa.Column('ultima_visita_confirmada_id', sa.Integer(), nullable=True),
    sa.Column('fecha_ultima_confirmacion', sa.Date(), nullable=True),
    sa.Column('confirmada_por_id', sa.Integer(), nullable=True),
    sa.Column('requiere_presupuesto', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['aprobado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['confirmada_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['instalacion_id'], ['instalaciones.id'], ),
    sa.ForeignKeyConstraint(['item_visita_id'], ['items_visita.id'], ),
    sa.ForeignKeyConstraint(['reabierto_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['resuelto_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['ultima_visita_confirmada_id'], ['visitas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repuestos_usados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_trabajo_id', sa.Integer(), nullable=False),
    sa.Column('repuesto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['orden_trabajo_id'], ['ordenes_trabajo.id'], ),
    sa.ForeignKeyConstraint(['repuesto_id'], ['repuestos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_visita_id', sa.Integer(), nullable=True),
    sa.Column('instalacion_id', sa.Integer(), nullable=True),
    sa.Column('equipo_id', sa.Integer(), nullable=True),
    sa.Column('observacion_id', sa.Integer(), nullable=True),
    sa.Column('campo_formulario', sa.String(length=100), nullable=True),
    sa.Column('nombre_archivo', sa.String(length=300), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('origen', sa.String(length=20), nullable=False),
    sa.Column('fecha_toma', sa.Date(), nullable=True),
    sa.Column('fecha_subida', sa.DateTime(), nullable=False),
    sa.Column('subido_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['instalacion_id'], ['instalaciones.id'], ),
    sa.ForeignKeyConstraint(['item_visita_id'], ['items_visita.id'], ),
    sa.ForeignKeyConstraint(['observacion_id'], ['observaciones.id'], ),
    sa.ForeignKeyConstraint(['subido_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presupuestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('observacion_id', sa.Integer(), nullable=False),
    sa.Column('ot_correctiva_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['observacion_id'], ['observaciones.id'], ),
    sa.ForeignKeyConstraint(['ot_correctiva_id'], ['ordenes_trabajo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('presupuestos_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presupuesto_id', sa.Integer(), nullable=False),
    sa.Column('estado_anterior', sa.String(length=20), nullable=True),
    sa.Column('estado_nuevo', sa.String(length=20), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('fecha_cambio', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuestos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presupuestos_audit')
    op.drop_table('presupuestos')
    op.drop_table('fotos')
    op.drop_table('repuestos_usados')
    op.drop_table('observaciones')
    op.drop_table('formularios')
    op.drop_table('ensayos_caudal')
    op.drop_table('coordinacion_audit')
    op.drop_table('solicitudes_coordinacion')
    op.drop_table('ordenes_trabajo')
    op.drop_table('items_visita')
    op.drop_table('visitas')
    op.drop_table('servicios_contrato')
    op.drop_table('curvas_fabrica')
    op.drop_table('notificaciones')
    op.drop_table('mensajes')
    op.drop_table('equipos')
    op.drop_table('contratos')
    op.drop_table('usuarios')
    op.drop_table('tipos_formulario')
    op.drop_table('instalaciones')
    op.drop_table('servicios_tipo')
    op.drop_table('repuestos')
    op.drop_table('clientes')
    op.drop_table('tipos_equipo')
    op.drop_table('empresas')
    # ### end Alembic commands ###
